# Generated by Django 5.1.1 on 2024-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('calificacion_atencion', models.CharField(max_length=20)),
                ('escuchado', models.BooleanField()),
                ('recomendacion', models.BooleanField()),
                ('calificacion_instalaciones', models.CharField(max_length=20)),
                ('experiencia_general', models.CharField(max_length=20)),
            ],
        ),
    ]
