# Generated by Django 5.1.1 on 2024-11-29 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marcacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora_marcado', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='marcacion.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
